### ISSUE TITLE
Where is the jQuery Foundation?

### ISSUE THREAD

**Issue by mathiasbynens** [hemanth/tc39-members#4]

**Comment by hemanth** [comment]
When the module was created there was no [NFP](http://www.ecma-international.org/memento/NFP.htm) section in memento, will be adding them all soon.

BTW was working on #2 as well.

**Comment by hemanth** [comment]
[here it is](https://github.com/hemanth/tc39-members/blob/master/members.json#L65)! Thanks for reporting :)
